import test from 'node:test';
import assert from 'node:assert/strict';
import {PRESETS,clone,newProject,newPage,makeObject,copyPage,validateBadge,boundary,outside,alignObjects,fitObjects,impose,number,parseCSV} from '../core.js';
import {pageSVG} from '../render.js';
import {validateProject,compactProject,checkCapacity} from '../files.js';
import {addDensity,exportProject} from '../export.js';
import {validateFonts,fontStyle,importFont,FONT_LIMIT} from '../fonts.js';
import {rotateCrop,cropSelection} from '../crop.js';
import {PAPER_SIZES,printPlan,sheetCapacity} from '../print-plan.js';
const measured=[['round75',86,86,75,75,70,70],['round58',70,70,58,58,54,54],['round44',54,54,44,44,40,40],['round32',44,44,32,32,29,29],['square50',61,61,50,50,46,46],['rect68',78,34,68,24,60,18],['rect80',85,70,80,53,76,49],['polaroid',60,90,54,86,52,84],['sticker35',35,35,35,35,33,33],['sticker71',71,22,71,22,69,20],['sticker84',84,29,84,29,82,27],['key55',55,25,55,25,53,23],['key27',27,40.5,27,40.5,25,38.5],['yoyo18',18,18,18,18,16,16],['yoyo22',22,22,22,22,20,20],['band',255,19,255,19,217,16]];
for(const [id,...sizes] of measured)test(`${id}: reference dimensions and rendering`,()=>{const b=PRESETS.find(p=>p.id===id);assert.deepEqual([b.w,b.h,b.faceW,b.faceH,b.safeW,b.safeH],sizes);validateBadge(b);const svg=pageSVG(newPage(b),{}, {guides:true});assert.ok(svg.includes(`width="${b.w}mm" height="${b.h}mm"`));for(const g of ['safe','face','cut'])assert.ok(svg.includes(`data-guide="${g}"`));});
test('wristband offset is 38 mm, rounded corners retained',()=>{const b=PRESETS.at(-1);assert.equal(boundary(b).x,38);const o={x:20,y:3,w:5,h:5,rotation:0};assert.equal(outside(o,b),true);alignObjects([o],b,'center');assert.equal(o.x,144);assert.equal(outside(o,b),false);assert.equal(outside({x:7.5,y:7.5,w:1,h:1,rotation:0},PRESETS[4]),true);});
test('numeric validation and invalid custom boundaries',()=>{for(const v of ['',NaN,Infinity,'bad',-1])assert.throws(()=>number(v,0,100));assert.equal(number('40.5',0,100),40.5);assert.throws(()=>number(1.5,1,10,true));assert.throws(()=>validateBadge({...PRESETS[1],safeX:9}));assert.throws(()=>validateBadge({...PRESETS[1],safeW:80}));});
test('copy page regenerates object and group IDs',()=>{const p=newPage();p.objects=[makeObject('text',p),makeObject('rect',p)];p.objects.forEach(o=>o.group='test');const c=copyPage(p);assert.notEqual(c.id,p.id);assert.notEqual(c.objects[0].id,p.objects[0].id);assert.equal(c.objects[0].group,c.objects[1].group);assert.notEqual(c.objects[0].group,'test');});
test('group centre keeps relative positions',()=>{const p=newPage(),a=makeObject('text',p),b=makeObject('text',p);b.x+=4;b.y+=9;alignObjects([a,b],p.badge,'center');assert.equal(b.x-a.x,4);assert.equal(b.y-a.y,9);fitObjects([a,b],p.badge);assert.ok(!outside(a,p.badge)&&!outside(b,p.badge));});
test('CSV handles quoted commas, escaped quotes, newlines and BOM',()=>{const csv=parseCSV('\uFEFFName,Code\r\n"A, B",001\r\n"C ""D""\nE",002\r\n');assert.deepEqual(csv.headers,['Name','Code']);assert.equal(csv.rows[0].Name,'A, B');assert.equal(csv.rows[0].Code,'001');assert.equal(csv.rows[1].Name,'C "D"\nE');assert.throws(()=>parseCSV('A,A\n1,2'));assert.throws(()=>parseCSV('A,B\n1'));assert.throws(()=>parseCSV('A\n"oops'));});
test('packing uses cut sizes, exact copy counts and bounds',()=>{const p=newPage();p.copies=9;assert.deepEqual(impose([p],210,297,5,2).map(s=>s.length),[8,1]);p.copies=25;assert.deepEqual(impose([p],330.2,482.6,5,2).map(s=>s.length),[24,1]);p.copies=500;const sheets=impose([p],330.2,482.6,5,2);assert.equal(sheets.flat().length,500);for(const s of sheets)for(const v of s){assert.ok(v.x>=5&&v.y>=5&&v.x+v.w<=325.2&&v.y+v.h<=477.6);}p.copies=501;assert.throws(()=>impose([p],210,297,5,2));});
test('project save/reopen is validated and preserves supported values',()=>{const p=newProject(),o=makeObject('text',p.pages[0]);o.text='Test <script>';o.fillOpacity=.4;p.pages[0].objects.push(o);const q=validateProject(compactProject(p));assert.equal(q.pages[0].objects[0].text,o.text);assert.equal(q.pages[0].objects[0].fillOpacity,.4);assert.ok(pageSVG(q.pages[0],q.assets).includes('&lt;script&gt;'));o.fill='url(https://example.com)';assert.throws(()=>validateProject(p));});
test('project limits and hostile inputs are rejected',()=>{const p=newProject();p.assets.a={data:'https://example.com/x.png',w:100,h:100};assert.throws(()=>validateProject(p));p.assets={};p.pages[0].objects.push({...makeObject('text',p.pages[0]),rotation:Infinity});assert.throws(()=>validateProject(p));p.pages=Array.from({length:101},()=>newPage());assert.throws(()=>checkCapacity(p));});
test('guides never leak into default production rendering',()=>{const p=newPage();const svg=pageSVG(p,{});assert.ok(!svg.includes('data-guide'));assert.ok(!svg.includes('>TOP<'));});
test('PNG DPI metadata is inserted with physical pixels/metre',()=>{const png=new Uint8Array(50);const out=addDensity(png,'png',300),v=new DataView(out.buffer);assert.equal(out.length,71);assert.equal(v.getUint32(33),9);assert.equal(v.getUint32(41),11811);assert.equal(v.getUint32(45),11811);assert.equal(out[49],1);});
test('JPEG JFIF density uses dots per inch',()=>{const a=new Uint8Array(20);a.set([255,216,255,224,0,16,74,70,73,70,0,1,1,0,0,1,0,1]);const out=addDensity(a,'jpg',600);assert.equal(out[13],1);assert.equal(new DataView(out.buffer).getUint16(14),600);assert.equal(new DataView(out.buffer).getUint16(16),600);});
test('per-page and total object limits reject excess',()=>{const p=newProject();p.pages[0].objects=Array.from({length:151},()=>makeObject('rect',p.pages[0]));assert.throws(()=>checkCapacity(p));p.pages=Array.from({length:14},()=>newPage());for(const page of p.pages)page.objects=Array.from({length:150},()=>makeObject('rect',page));assert.throws(()=>checkCapacity(p));});
test('preset identity survives save/reopen',()=>{const p=newProject();const q=validateProject(p);assert.equal(q.pages[0].badge.id,'round58');});
test('fit keeps text within persistable parameter limits',()=>{const p=newProject(),o=makeObject('text',p.pages[0]);o.w=o.h=.1;o.fontSize=300;o.arcRadius=1000;p.pages[0].objects.push(o);fitObjects([o],p.pages[0].badge);assert.ok(o.fontSize<=300&&o.arcRadius<=1000);validateProject(p);});
test('fit rejects tiny members without mutating the selection',()=>{const p=newPage(),a=makeObject('rect',p),b=makeObject('rect',p);a.w=a.h=.1;b.x=1900;const before=clone([a,b]);assert.throws(()=>fitObjects([a,b],p.badge));assert.deepEqual([a,b],before);});
test('CSV rejects trailing text after closing quotes',()=>{for(const s of ['A\n"foo"bar','A\n""x','A\n"foo""'])assert.throws(()=>parseCSV(s));assert.equal(parseCSV('\uFEFF"A"\n"a""b"').rows[0].A,'a"b');});
test('crop rotation is reversible and preserves area',()=>{const c={x:.1,y:.2,w:.3,h:.5};let r=c;for(let i=0;i<4;i++)r=rotateCrop(r);for(const k of Object.keys(c))assert.ok(Math.abs(c[k]-r[k])<1e-12);const ccw=rotateCrop(rotateCrop(c),false);assert.ok(Math.abs(ccw.y-c.y)<1e-12);});
test('crop selections stay in bounds for all drag directions',()=>{for(const a of [{x:0,y:0},{x:1,y:1},{x:.2,y:.8},{x:.9,y:.2}])for(const b of [{x:1,y:1},{x:0,y:0},{x:.8,y:.1}])for(const ratio of [null,1,4/3,.2,8]){const c=cropSelection(a,b,ratio);if(!c)continue;assert.ok(c.x>=-1e-9&&c.y>=-1e-9&&c.x+c.w<=1+1e-9&&c.y+c.h<=1+1e-9);if(ratio)assert.ok(Math.abs(c.w/c.h-ratio)<1e-9);}});
test('zero-area crop clicks do not corrupt existing crop',()=>{assert.equal(cropSelection({x:1,y:1},{x:1,y:1}),null);assert.throws(()=>cropSelection({x:0,y:0},{x:1,y:1},0));});
test('custom fonts survive compact project and SVG export',()=>{const p=newProject(),o=makeObject('text',p.pages[0]);o.font='pmfont_test';p.pages[0].objects.push(o);p.fonts={pmfont_test:{name:'Sample',data:'data:font/ttf;base64,AAEAAA=='},pmfont_unused:{name:'Unused',data:'data:font/woff;base64,d09GRg=='}};const compact=compactProject(p);assert.deepEqual(Object.keys(compact.fonts),['pmfont_test']);const q=validateProject(compact);assert.equal(q.pages[0].objects[0].font,'pmfont_test');assert.ok(pageSVG(q.pages[0],q.assets,{fonts:q.fonts}).includes('@font-face'));assert.ok(!pageSVG(q.pages[0],q.assets,{fonts:q.fonts,overlay:true}).includes('@font-face'));});
test('embedded fonts reject external URLs and CSS injection',()=>{assert.throws(()=>validateFonts({pmfont_test:{data:'https://example.com/font.woff'}}));assert.throws(()=>fontStyle({"pmfont_x';}body{color:red}":{data:'data:font/ttf;base64,AAEAAA=='}}));assert.throws(()=>validateFonts({pmfont_test:{data:'data:font/ttf;base64,'+'A'.repeat(FONT_LIMIT)}}));});
test('font import rejects bad signatures and excessive size',async()=>{await assert.rejects(importFont(new File(['bad data'],'bad.ttf')));await assert.rejects(importFont(new File([new Uint8Array(4*1024*1024+1)],'big.ttf')));});
test('inch paper presets and one-sheet capacity are exact',()=>{assert.deepEqual(PAPER_SIZES['12x18'],[304.8,457.2]);assert.deepEqual(PAPER_SIZES['13x19'],[330.2,482.6]);for(const size of Object.values(PAPER_SIZES)){const p=newPage(),n=sheetCapacity(p.badge,...size,5,2);p.copies=n;assert.equal(impose([p],...size,5,2).length,1);p.copies++;assert.equal(impose([p],...size,5,2).length,2);}assert.equal(sheetCapacity(newPage().badge,60,60,5,2),0);});
test('export quantities override copies without changing saved pages',()=>{const p=newProject(),id=p.pages[0].id,before=clone(p);const result=printPlan(p,{w:304.8,h:457.2,margin:5,gap:2,quantities:{[id]:25}});assert.equal(result.total,25);assert.deepEqual(result.sheets.map(s=>s.length),[24,1]);assert.deepEqual(p,before);});
test('gangup mixes designs but separate mode starts new sheets',()=>{const p=newProject();p.pages.push(newPage());const quantities=Object.fromEntries(p.pages.map((p,i)=>[p.id,i?7:5])),opts={w:330.2,h:482.6,margin:5,gap:2,quantities};const mixed=printPlan(p,opts),separate=printPlan(p,{...opts,layout:'separate'});assert.deepEqual(mixed.sheets.map(s=>s.length),[12]);assert.deepEqual(separate.sheets.map(s=>s.length),[5,7]);assert.ok(separate.sheets[1].every(i=>i.page===1));});
test('zero quantities skip designs and current scope excludes others',()=>{const p=newProject();p.pages.push(newPage());const opts={w:210,h:297,margin:5,gap:2,quantities:{[p.pages[0].id]:0,[p.pages[1].id]:9}};const plan=printPlan(p,opts);assert.equal(plan.pages[0].id,p.pages[1].id);assert.deepEqual(plan.sheets.map(s=>s.length),[8,1]);assert.ok(plan.sheets.flat().every(i=>i.page===0));assert.throws(()=>printPlan(p,{...opts,current:0}),/at least one/);assert.equal(printPlan(p,{...opts,current:1}).total,9);});
test('export rejects invalid and excessive quantities for both layouts',()=>{const p=newProject();p.pages.push(newPage());const opts={w:330.2,h:482.6,margin:5,gap:2};for(const layout of ['gangup','separate']){for(const value of ['',-1,.5,501,NaN])assert.throws(()=>printPlan(p,{...opts,layout,quantities:{[p.pages[0].id]:value}}));assert.throws(()=>printPlan(p,{...opts,layout,quantities:Object.fromEntries(p.pages.map(p=>[p.id,300]))}),/500 total/);}assert.throws(()=>printPlan(p,{...opts,layout:'wrong'}));});
test('mixed-size gangup keeps exact dimensions and stays within landscape sheets',()=>{const p=newProject();p.pages.push(newPage(PRESETS[5]));p.pages[0].copies=25;p.pages[1].copies=17;const plan=printPlan(p,{w:482.6,h:330.2,margin:5,gap:3});assert.equal(plan.sheets.flat().length,42);for(const sheet of plan.sheets)for(const item of sheet){const b=plan.pages[item.page].badge;assert.equal(item.w,b.w);assert.equal(item.h,b.h);assert.ok(item.x>=5&&item.y>=5&&item.x+item.w<=477.600001&&item.y+item.h<=325.200001);}assert.throws(()=>printPlan(p,{w:60,h:60,margin:5,gap:3}),/does not fit/);});
test('all presets pack without overlap on supported paper at both orientations',()=>{
  for(const size of Object.values(PAPER_SIZES))for(const landscape of [false,true]){
    const [w,h]=landscape?[...size].reverse():size;
    const p=newProject();p.pages=PRESETS.filter(b=>b.w<=w-10&&b.h<=h-10).map(b=>({...newPage(b),copies:3}));
    for(const layout of ['gangup','separate']){
      const plan=printPlan(p,{w,h,margin:5,gap:2,layout});assert.equal(plan.total,p.pages.length*3);
      for(const sheet of plan.sheets)for(const [i,a] of sheet.entries()){
        assert.ok(a.x>=5&&a.y>=5&&a.x+a.w<=w-5+1e-8&&a.y+a.h<=h-5+1e-8);
        for(const b of sheet.slice(i+1))assert.ok(a.x+a.w+2<=b.x+1e-8||b.x+b.w+2<=a.x+1e-8||a.y+a.h+2<=b.y+1e-8||b.y+b.h+2<=a.y+1e-8);
      }
    }
  }
});
test('a cancelled export stops before rasterisation or download in every format',async()=>{
  const controller=new AbortController();controller.abort();
  for(const format of ['pdf','png','jpg','svg'])await assert.rejects(exportProject(newProject(),{format},()=>assert.fail('No work should start'),controller.signal),/Export cancelled/);
});
