import {PRESETS,newProject,newPage,makeObject,validateBadge,number,uid,clone} from './core.js';
import {validateFonts} from './fonts.js';
import {documentName} from './naming.js';
export {localStore as autosaveStore} from './storage.js';
export const LIMITS={pages:100,objects:150,total:2000,assets:60*1024*1024,pixels:24000000,importPixels:96000000};
export function download(data,name,type){const url=URL.createObjectURL(data instanceof Blob?data:new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),5000);}
export const safeName=s=>documentName(s);
export function loadImage(src){return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(new Error('Cannot decode this image.'));im.src=src;});}
export const readData=file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(new Error('Cannot read file.'));r.readAsDataURL(file);});
export function canvasFor(w,h){w=Math.ceil(w);h=Math.ceil(h);if(w<1||h<1||w*h>LIMITS.pixels||w>16000||h>16000)throw new Error('Image exceeds the 24 megapixel / 16,000 pixel side limit. Reduce size or DPI.');const c=document.createElement('canvas');c.width=w;c.height=h;return c;}
export function compactProject(p){const c={version:1,name:p.name,pages:clone(p.pages),assets:{},fonts:{}};for(const page of c.pages)for(const o of page.objects){if(o.asset)c.assets[o.asset]=p.assets[o.asset];if(p.fonts?.[o.font])c.fonts[o.font]=p.fonts[o.font];}return c;}
export function checkCapacity(p){if(p.pages.length>LIMITS.pages||p.pages.some(p=>p.objects.length>LIMITS.objects)||p.pages.reduce((n,p)=>n+p.objects.length,0)>LIMITS.total)throw new Error('Project limit: 100 pages, 150 objects/page, 2,000 objects total.');const bytes=Object.values(p.assets).reduce((n,a)=>n+a.data.length,0);if(bytes>LIMITS.assets)throw new Error('Project image storage exceeds 60 MB. Use a smaller batch.');}
function appendAsset(assets,asset,budget=LIMITS.assets){if(assets.reduce((n,a)=>n+a.data.length,asset.data.length)>budget)throw new Error('This import exceeds the remaining project image storage. Choose fewer or smaller files.');assets.push(asset);}
function importBudget(options={}){let pixels=options.remainingPixels??LIMITS.importPixels;return {check(w,h){options.signal?.throwIfAborted();pixels-=Math.ceil(w)*Math.ceil(h);if(pixels<0)throw new Error('Import exceeds the remaining 96 MP project image budget. Remove unused images or start a smaller project.');},bytes:options.remainingBytes??LIMITS.assets};}
const choices={type:['text','curve','image','qr','barcode','rect','circle','triangle','polygon','star','hexagon','diamond','heart','line','arrow'],fillMode:['solid','linear','radial'],strokeStyle:['solid','dashed','dotted'],fit:['cover','contain','stretch'],bleed:['none','stretch','blur','spin'],filter:['none','grayscale','sepia','invert'],cropShape:['rect','round'],align:['start','middle','end'],barcode:['CODE128','CODE39','EAN13','EAN8','UPC','ITF','MSI','pharmacode']};
export const ranges={x:[-2000,2000],y:[-2000,2000],w:[.1,2000],h:[.1,2000],rotation:[-3600,3600],opacity:[0,1],fillOpacity:[0,1],strokeOpacity:[0,1],angle:[0,360],strokeWidth:[0,20],radius:[0,1000],sides:[3,30,true],inner:[.05,.95],fontSize:[.1,300],spacing:[-20,100],arcRadius:[.1,1000],arcStart:[0,100],shadowBlur:[0,100],shadowX:[-100,100],shadowY:[-100,100],shadowOpacity:[0,1],brightness:[0,200],contrast:[0,200],saturation:[0,200]};
export function validateProject(raw){
  if(raw?.version!==1||!Array.isArray(raw.pages)||!raw.pages.length||raw.pages.length>LIMITS.pages)throw new Error('Invalid project format or page count.');
  const p=newProject();p.name=String(raw.name||'Imported badges').slice(0,120);p.pages=[];p.assets={};p.fonts=validateFonts(raw.fonts);const assetIds=new Map();
  for(const [key,a] of Object.entries(raw.assets||{})){if(typeof a.data!=='string'||!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(a.data))throw new Error('Project assets must be embedded PNG, JPG or WebP images.');number(a.w,1,16000,true);number(a.h,1,16000,true);if(a.w*a.h>LIMITS.pixels)throw new Error('Project image too large.');const id=uid();assetIds.set(key,id);p.assets[id]={data:a.data,w:a.w,h:a.h};}
  const color=v=>{if(!/^#[0-9a-f]{6}$/i.test(v))throw new Error('Invalid colour value.');return v;};
  for(const old of raw.pages){const b={id:'custom',name:String(old.badge?.name||'Badge').slice(0,100),shape:old.badge?.shape};for(const key of ['w','h','faceW','faceH','safeW','safeH','cornerRadius','safeX','safeY'])if(old.badge[key]!=null)b[key]=number(old.badge[key],0,1000);validateBadge(b);const page=newPage(b);page.name=String(old.name||'Badge').slice(0,100);page.copies=number(old.copies,1,500,true);page.bg=color(old.bg);page.bg2=color(old.bg2);page.bgAngle=number(old.bgAngle,0,360);if(!['solid','linear','transparent'].includes(old.bgMode))throw new Error('Invalid background mode.');page.bgMode=old.bgMode;
    if(!Array.isArray(old.objects)||old.objects.length>LIMITS.objects)throw new Error('Too many objects.');const groups=new Map();
    for(const source of old.objects){if(!choices.type.includes(source.type))throw new Error('Unsupported object.');const o=makeObject(source.type,page);for(const [k,r] of Object.entries(ranges))if(source[k]!=null)o[k]=number(source[k],...r);for(const [k,values] of Object.entries(choices))if(source[k]!=null){if(!values.includes(source[k]))throw new Error('Invalid object option.');o[k]=source[k];}for(const k of ['fill','fill2','stroke','shadowColor'])o[k]=color(source[k]);for(const k of ['text','value','font','name','field'])if(source[k]!=null)o[k]=String(source[k]).slice(0,k==='text'||k==='value'?10000:150);for(const k of ['bold','italic','underline','strike','arcFlip','shadow','locked','hidden','showValue'])o[k]=source[k]===true;
      o.qrCaption=source.qrCaption===true;o.scaleBorders=source.scaleBorders===true;
      o.photoRotation=source.photoRotation??0;if(![0,90,180,270].includes(o.photoRotation))throw new Error('Invalid photo rotation.');
      if(source.group){if(!groups.has(source.group))groups.set(source.group,uid());o.group=groups.get(source.group);}
      if(o.type==='image'){o.asset=assetIds.get(source.asset);if(!o.asset)throw new Error('Missing image asset.');const c=source.crop;o.crop={x:number(c.x,0,1),y:number(c.y,0,1),w:number(c.w,.0001,1),h:number(c.h,.0001,1)};if(c.x+c.w>1.000001||c.y+c.h>1.000001)throw new Error('Invalid crop bounds.');}
      page.objects.push(o);
    }const preset=PRESETS.find(p=>p.id===old.badge.id);if(preset&&['shape','w','h','faceW','faceH','safeW','safeH','cornerRadius','safeX','safeY'].every(k=>(preset[k]??null)===(b[k]??null)))page.badge.id=preset.id;p.pages.push(page);
  }checkCapacity(p);return p;
}
export async function importImages(files,options={}){
  options.signal?.throwIfAborted();if(files.length>(options.remainingItems??Infinity))throw new Error('Not enough project space for this batch.');
  const budget=importBudget(options),assets=[];for(const file of files){options.signal?.throwIfAborted();options.progress?.(`Reading image ${assets.length+1}/${files.length}: ${file.name}`);await new Promise(r=>setTimeout(r,0));options.signal?.throwIfAborted();if(file.size>25*1024*1024)throw new Error(`${file.name}: file exceeds 25 MB.`);let data;
    if(file.type==='image/svg+xml'||/\.svg$/i.test(file.name)){
      const doc=new DOMParser().parseFromString(await file.text(),'image/svg+xml');if(doc.querySelector('parsererror'))throw new Error('Invalid SVG.');
      const safeCss=s=>!/[\\]|@import/i.test(s)&&!Array.from(s.matchAll(/url\(([^)]*)\)/gi)).some(m=>!/^['"]?#[\w-]+['"]?$/.test(m[1].trim()));
      for(const el of Array.from(doc.querySelectorAll('*'))){if(['script','foreignobject','iframe','animate','animatetransform','set'].includes(el.localName.toLowerCase())){el.remove();continue;}if(el.localName==='style'&&!safeCss(el.textContent))throw new Error('SVG uses unsupported external styles. Export it as PNG first.');for(const a of Array.from(el.attributes)){if(/^on/i.test(a.name))el.removeAttribute(a.name);else if(/href$/i.test(a.name)&&!/^#[\w-]+$/.test(a.value)&&!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(a.value))throw new Error('SVG uses external content. Embed it or export as PNG first.');else if(!safeCss(a.value))throw new Error('SVG uses unsupported external styles. Export it as PNG first.');}}
      data='data:image/svg+xml;base64,'+btoa(unescape(encodeURIComponent(new XMLSerializer().serializeToString(doc))));
    }else{if(!/^image\/(png|jpeg|webp)$/.test(file.type))throw new Error('Use PNG, JPG, WebP or SVG.');data=await readData(file);}
    const im=await loadImage(data),scale=data.startsWith('data:image/svg')?Math.max(1,2048/Math.max(im.naturalWidth,im.naturalHeight)):1;budget.check(im.naturalWidth*scale,im.naturalHeight*scale);const c=canvasFor(im.naturalWidth*scale,im.naturalHeight*scale);try{c.getContext('2d').drawImage(im,0,0,c.width,c.height);appendAsset(assets,{name:file.name,data:c.toDataURL('image/png'),w:c.width,h:c.height},budget.bytes);}finally{c.width=c.height=0;}
  }return assets;
}
export async function importPDFs(files,progress=()=>{},options={}){
  options.signal?.throwIfAborted();const budget=importBudget(options);
  const pdfjs=await import('./vendor/pdfjs/build/pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc=new URL('./vendor/pdfjs/build/pdf.worker.min.mjs',import.meta.url).href;const assets=[];
  for(const file of files){options.signal?.throwIfAborted();if(file.size>50*1024*1024)throw new Error('PDF exceeds 50 MB.');const job=pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer()),cMapUrl:new URL('./vendor/pdfjs/cmaps/',import.meta.url).href,cMapPacked:true,standardFontDataUrl:new URL('./vendor/pdfjs/standard_fonts/',import.meta.url).href,wasmUrl:new URL('./vendor/pdfjs/wasm/',import.meta.url).href,isEvalSupported:false});
    try{const doc=await job.promise;options.signal?.throwIfAborted();if(doc.numPages+assets.length>20)throw new Error('Import at most 20 PDF pages per batch.');if(doc.numPages+assets.length>(options.remainingItems??Infinity))throw new Error('Not enough project space for these PDF pages.');for(let n=1;n<=doc.numPages;n++){options.signal?.throwIfAborted();progress(`Reading ${file.name}, page ${n}/${doc.numPages}`);const p=await doc.getPage(n),vp=p.getViewport({scale:300/72});let c,task;const abort=()=>task?.cancel();try{budget.check(vp.width,vp.height);c=canvasFor(vp.width,vp.height);task=p.render({canvasContext:c.getContext('2d'),viewport:vp});options.signal?.addEventListener('abort',abort,{once:true});await task.promise;options.signal?.throwIfAborted();appendAsset(assets,{name:`${file.name} / ${n}`,data:c.toDataURL('image/png'),w:c.width,h:c.height},budget.bytes);}finally{options.signal?.removeEventListener('abort',abort);if(c)c.width=c.height=0;p.cleanup();}}}finally{await job.destroy();}
  }return assets;
}
